/**
 * 3D Model Export Utilities
 * Handles exporting 3D models to various formats (STL, GLTF, GLB, etc.)
 */

import * as THREE from 'three';
import { STLExporter } from 'three/examples/jsm/exporters/STLExporter.js';
import { GLTFExporter } from 'three/examples/jsm/exporters/GLTFExporter.js';

export interface ExportOptions {
  format: 'step' | 'iges' | 'stl' | 'glb' | 'gltf' | 'obj';
  binary?: boolean;
  onProgress?: (progress: number) => void;
}

export interface ExportResult {
  success: boolean;
  data?: ArrayBuffer | DataView | string;
  filename: string;
  mimeType: string;
  error?: string;
}

/**
 * Export 3D scene to STL format
 * Supports both ASCII and binary STL formats
 */
export async function exportToSTL(
  scene: THREE.Object3D,
  filename: string,
  binary: boolean = false,
): Promise<ExportResult> {
  try {
    const exporter = new STLExporter();

    // Clone scene to avoid modifying original
    const sceneToExport = scene.clone();

    // Parse the scene (exporter expects Object3D, not geometry)
    const data = exporter.parse(sceneToExport, { binary });
    const mimeType = binary ? 'application/octet-stream' : 'text/plain';
    const outputFilename = filename.replace(/\.[^/.]+$/, '') + '.stl';

    return {
      success: true,
      data,
      filename: outputFilename,
      mimeType,
    };
  } catch (error) {
    return {
      success: false,
      filename,
      mimeType: 'application/octet-stream',
      error: `Failed to export STL: ${error instanceof Error ? error.message : String(error)}`,
    };
  }
}

/**
 * Export 3D scene to GLTF/GLB format
 * GLB is the binary version of GLTF
 */
export async function exportToGLTF(
  scene: THREE.Object3D,
  filename: string,
  binary: boolean = true,
  onProgress?: (progress: number) => void,
): Promise<ExportResult> {
  return new Promise((resolve) => {
    try {
      const exporter = new GLTFExporter();

      const options: Record<string, unknown> = {
        binary,
        animations: extractAnimations(scene),
        maxTextureSize: 2048,
      };

      // Track progress manually
      let progressTracked = 0;
      const progressInterval = setInterval(() => {
        if (progressTracked < 90) {
          progressTracked += Math.random() * 20;
          onProgress?.(Math.min(progressTracked, 90));
        }
      }, 100);

      exporter.parse(
        scene,
        (result) => {
          clearInterval(progressInterval);
          onProgress?.(100);

          let data: ArrayBuffer | string;
          let mimeType: string;
          const extension = binary ? '.glb' : '.gltf';
          const outputFilename = filename.replace(/\.[^/.]+$/, '') + extension;

          if (binary) {
            data = result as ArrayBuffer;
            mimeType = 'application/octet-stream';
          } else {
            data = JSON.stringify(result, null, 2);
            mimeType = 'application/json';
          }

          resolve({
            success: true,
            data,
            filename: outputFilename,
            mimeType,
          });
        },
        (_error) => {
          // Error callback - just log it
          console.error('GLTF Export error:', _error);
        },
        options as Record<string, unknown>,
      );

      // Set timeout for export completion
      setTimeout(() => {
        clearInterval(progressInterval);
        resolve({
          success: false,
          filename,
          mimeType: 'application/octet-stream',
          error: 'GLTF export timeout',
        });
      }, 30000); // 30 second timeout
    } catch (error) {
      resolve({
        success: false,
        filename,
        mimeType: 'application/octet-stream',
        error: `Failed to export GLTF: ${error instanceof Error ? error.message : String(error)}`,
      });
    }
  });
}

/**
 * Export 3D scene to OBJ format
 * Basic OBJ export (geometry only, no materials)
 */
export async function exportToOBJ(
  scene: THREE.Object3D,
  filename: string,
): Promise<ExportResult> {
  try {
    const geometries: THREE.BufferGeometry[] = [];
    let vertexOffset = 0;
    let objData = '# Generated by TSplineForge\n';
    objData += `# File: ${filename}\n`;
    objData += `# Date: ${new Date().toISOString()}\n\n`;

    // Traverse scene and collect geometries
    scene.traverse((child) => {
      if (child instanceof THREE.Mesh) {
        geometries.push(child.geometry as THREE.BufferGeometry);
      }
    });

    if (geometries.length === 0) {
      throw new Error('No geometries found in scene');
    }

    // Convert geometries to OBJ format
    geometries.forEach((geometry, meshIndex) => {
      objData += `g Mesh_${meshIndex}\n`;

      // Get position attribute
      const positionAttribute = geometry.getAttribute('position');
      if (positionAttribute) {
        const positions = positionAttribute.array as Float32Array;
        for (let i = 0; i < positions.length; i += 3) {
          objData += `v ${positions[i]} ${positions[i + 1]} ${positions[i + 2]}\n`;
        }
      }

      // Get index or create faces
      const index = geometry.getIndex();
      if (index) {
        const indices = index.array as Uint32Array | Uint16Array | Uint8Array;
        for (let i = 0; i < indices.length; i += 3) {
          const a = (indices[i] as number) + vertexOffset + 1;
          const b = (indices[i + 1] as number) + vertexOffset + 1;
          const c = (indices[i + 2] as number) + vertexOffset + 1;
          objData += `f ${a} ${b} ${c}\n`;
        }
      }

      vertexOffset += (positionAttribute?.array as Float32Array).length / 3;
    });

    const outputFilename = filename.replace(/\.[^/.]+$/, '') + '.obj';

    return {
      success: true,
      data: objData,
      filename: outputFilename,
      mimeType: 'text/plain',
    };
  } catch (error) {
    return {
      success: false,
      filename,
      mimeType: 'text/plain',
      error: `Failed to export OBJ: ${error instanceof Error ? error.message : String(error)}`,
    };
  }
}

/**
 * Export 3D scene to STEP format
 * Creates a basic STEP file with geometric representation
 */
export async function exportToSTEP(
  scene: THREE.Object3D,
  filename: string,
  options?: { tolerance?: number; unit?: string; onProgress?: (progress: number) => void },
): Promise<ExportResult> {
  return new Promise((resolve) => {
    try {
      options?.onProgress?.(10);

      // Collect mesh data
      const meshes: Array<{ geometry: THREE.BufferGeometry; matrix: THREE.Matrix4 }> = [];
      scene.traverse((child) => {
        if (child instanceof THREE.Mesh && child.geometry) {
          meshes.push({
            geometry: child.geometry as THREE.BufferGeometry,
            matrix: child.matrixWorld,
          });
        }
      });

      if (meshes.length === 0) {
        throw new Error('No geometry found in scene');
      }

      options?.onProgress?.(30);

      // Generate STEP file content
      const stepData = generateSTEPContent(meshes, filename, {
        tolerance: options?.tolerance ?? 0.01,
        unit: options?.unit ?? 'MM',
      });

      options?.onProgress?.(80);

      const outputFilename = filename.replace(/\.[^/.]+$/, '') + '.step';

      options?.onProgress?.(100);

      resolve({
        success: true,
        data: stepData,
        filename: outputFilename,
        mimeType: 'application/octet-stream',
      });
    } catch (error) {
      resolve({
        success: false,
        filename,
        mimeType: 'application/octet-stream',
        error: `Failed to export STEP: ${error instanceof Error ? error.message : String(error)}`,
      });
    }
  });
}

/**
 * Export 3D scene to IGES format
 * Creates a basic IGES file with geometric representation
 */
export async function exportToIGES(
  scene: THREE.Object3D,
  filename: string,
  options?: { tolerance?: number; unit?: string; onProgress?: (progress: number) => void },
): Promise<ExportResult> {
  return new Promise((resolve) => {
    try {
      options?.onProgress?.(10);

      // Collect mesh data
      const meshes: Array<{ geometry: THREE.BufferGeometry; matrix: THREE.Matrix4 }> = [];
      scene.traverse((child) => {
        if (child instanceof THREE.Mesh && child.geometry) {
          meshes.push({
            geometry: child.geometry as THREE.BufferGeometry,
            matrix: child.matrixWorld,
          });
        }
      });

      if (meshes.length === 0) {
        throw new Error('No geometry found in scene');
      }

      options?.onProgress?.(30);

      // Generate IGES file content
      const igesData = generateIGESContent(meshes, filename, {
        tolerance: options?.tolerance ?? 0.01,
        unit: options?.unit ?? 'MM',
      });

      options?.onProgress?.(80);

      const outputFilename = filename.replace(/\.[^/.]+$/, '') + '.iges';

      options?.onProgress?.(100);

      resolve({
        success: true,
        data: igesData,
        filename: outputFilename,
        mimeType: 'application/octet-stream',
      });
    } catch (error) {
      resolve({
        success: false,
        filename,
        mimeType: 'application/octet-stream',
        error: `Failed to export IGES: ${error instanceof Error ? error.message : String(error)}`,
      });
    }
  });
}

/**
 * Generate STEP file content from meshes
 */
function generateSTEPContent(
  meshes: Array<{ geometry: THREE.BufferGeometry; matrix: THREE.Matrix4 }>,
  filename: string,
  _options: { tolerance: number; unit: string },
): string {
  const lines: string[] = [];

  // STEP header
  lines.push('ISO-10303-21;');
  lines.push('HEADER;');
  lines.push(`FILE_DESCRIPTION(('CAD Model exported by TSplineForge'),`);
  lines.push(`  '2;1',`);
  lines.push(`  ('${new Date().toISOString().split('T')[0]}'),`);
  lines.push(`  (''),`);
  lines.push(`  (''),`);
  lines.push(`  'Unknown',`);
  lines.push(`  'TSplineForge',`);
  lines.push(`  '');`);

  lines.push(`FILE_NAME('${filename}',`);
  lines.push(`  '${new Date().toISOString()}',`);
  lines.push(`  (''),`);
  lines.push(`  (''),`);
  lines.push(`  'Unknown',`);
  lines.push(`  'Unknown',`);
  lines.push(`  '');`);

  lines.push(`FILE_SCHEMA(('AP203_CONFIGURATION_CONTROLLED_3D_DESIGN_OF_MECHANICAL_PARTS_AND_ASSEMBLIES'));`);
  lines.push('ENDSEC;');

  // Data section
  lines.push('DATA;');

  let entityId = 1;
  const triangles: Array<{ vertices: THREE.Vector3[]; normal: THREE.Vector3 }> = [];

  // Convert meshes to triangles
  meshes.forEach((mesh) => {
    const positionAttribute = mesh.geometry.getAttribute('position');
    if (!positionAttribute) return;

    const positions = positionAttribute.array as Float32Array;
    const index = mesh.geometry.getIndex();

    if (index) {
      const indices = index.array as Uint32Array | Uint16Array;
      for (let i = 0; i < indices.length; i += 3) {
        const a = indices[i] * 3;
        const b = indices[i + 1] * 3;
        const c = indices[i + 2] * 3;

        const v0 = new THREE.Vector3(positions[a], positions[a + 1], positions[a + 2]).applyMatrix4(mesh.matrix);
        const v1 = new THREE.Vector3(positions[b], positions[b + 1], positions[b + 2]).applyMatrix4(mesh.matrix);
        const v2 = new THREE.Vector3(positions[c], positions[c + 1], positions[c + 2]).applyMatrix4(mesh.matrix);

        const edge1 = new THREE.Vector3().subVectors(v1, v0);
        const edge2 = new THREE.Vector3().subVectors(v2, v0);
        const normal = new THREE.Vector3().crossVectors(edge1, edge2).normalize();

        triangles.push({ vertices: [v0, v1, v2], normal });
      }
    }
  });

  // Write triangles as polyfaces (simplified STEP representation)
  triangles.forEach((tri) => {
    const pointIds: number[] = [];
    tri.vertices.forEach((vertex) => {
      lines.push(`#${entityId}=CARTESIAN_POINT('',(${vertex.x.toFixed(6)},${vertex.y.toFixed(6)},${vertex.z.toFixed(6)}));`);
      pointIds.push(entityId);
      entityId++;
    });

    lines.push(`#${entityId}=POLYLOOP('',(#${pointIds[0]},#${pointIds[1]},#${pointIds[2]}));`);
    entityId++;
  });

  lines.push('ENDSEC;');
  lines.push('END-ISO-10303-21;');

  return lines.join('\n');
}

/**
 * Generate IGES file content from meshes
 */
function generateIGESContent(
  meshes: Array<{ geometry: THREE.BufferGeometry; matrix: THREE.Matrix4 }>,
  filename: string,
  options: { tolerance: number; unit: string },
): string {
  const lines: string[] = [];

  // IGES header section
  lines.push('                                                                        S      1');
  lines.push(`1H,,1H,,13HUntitled Model,7HTSplineForge,32,308,15,308,15,${options.unit},1,0.01,15H${new Date().toISOString()},1.E-07,1000,15H${new Date().toISOString()},,,11H,0,0,11H,0,0,0,0,0;     G      1`);

  // Collect triangles
  let lineCount = 2;
  const triangles: Array<{ vertices: THREE.Vector3[] }> = [];

  meshes.forEach((mesh) => {
    const positionAttribute = mesh.geometry.getAttribute('position');
    if (!positionAttribute) return;

    const positions = positionAttribute.array as Float32Array;
    const index = mesh.geometry.getIndex();

    if (index) {
      const indices = index.array as Uint32Array | Uint16Array;
      for (let i = 0; i < indices.length; i += 3) {
        const a = indices[i] * 3;
        const b = indices[i + 1] * 3;
        const c = indices[i + 2] * 3;

        const v0 = new THREE.Vector3(positions[a], positions[a + 1], positions[a + 2]).applyMatrix4(mesh.matrix);
        const v1 = new THREE.Vector3(positions[b], positions[b + 1], positions[b + 2]).applyMatrix4(mesh.matrix);
        const v2 = new THREE.Vector3(positions[c], positions[c + 1], positions[c + 2]).applyMatrix4(mesh.matrix);

        triangles.push({ vertices: [v0, v1, v2] });
      }
    }
  });

  // Write triangles as polyfaces (simplified IGES representation)
  let directoryCount = 2;
  const dataLines: string[] = [];

  triangles.forEach((tri, idx) => {
    const type = 104; // Polyface
    dataLines.push(`${type}       ${idx * 2 + 1}H ,4HFace,0,0,0,4,${tri.vertices[0].x.toFixed(6)},${tri.vertices[0].y.toFixed(6)},${tri.vertices[0].z.toFixed(6)},`);
    directoryCount += 2;
  });

  // Terminate section
  lines.push('S      1');

  // Directory entry section
  triangles.forEach((tri, idx) => {
    const type = 104;
    const lineNum = idx * 2 + 2;
    lines.push(`${type}       1       0       0       0       0       0       000000000D${String(lineNum).padStart(7)}`);
    lines.push(`104       0       0       2       0                               0D${String(lineNum + 1).padStart(7)}`);
  });

  lineCount = lines.length + dataLines.length;
  lines.push(`S${String(1).padStart(7)}G${String(1).padStart(7)}D${String(directoryCount).padStart(7)}P${String(lineCount + 1).padStart(7)}${String(lineCount).padStart(8)}`);

  return lines.join('\n');
}

/**
 * Download exported file to client
 */
export function downloadFile(
  data: ArrayBuffer | DataView | string,
  filename: string,
  mimeType: string,
): void {
  let blobParts: BlobPart[];

  if (typeof data === 'string') {
    blobParts = [data];
  } else if (data instanceof DataView) {
    // Convert DataView to Uint8Array to avoid SharedArrayBuffer issues
    const uint8Array = new Uint8Array(data.buffer, data.byteOffset, data.byteLength);
    blobParts = [uint8Array as unknown as BlobPart];
  } else {
    blobParts = [data as unknown as BlobPart];
  }

  const blob = new Blob(blobParts, { type: mimeType });

  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

/**
 * Export with automatic download
 */
export async function exportAndDownload(
  scene: THREE.Object3D,
  filename: string,
  options: ExportOptions,
): Promise<ExportResult> {
  let result: ExportResult;

  switch (options.format) {
    case 'step':
      result = await exportToSTEP(scene, filename, { onProgress: options.onProgress });
      break;
    case 'iges':
      result = await exportToIGES(scene, filename, { onProgress: options.onProgress });
      break;
    case 'stl':
      result = await exportToSTL(scene, filename, options.binary ?? true);
      break;
    case 'glb':
      result = await exportToGLTF(scene, filename, true, options.onProgress);
      break;
    case 'gltf':
      result = await exportToGLTF(scene, filename, false, options.onProgress);
      break;
    case 'obj':
      result = await exportToOBJ(scene, filename);
      break;
    default:
      result = {
        success: false,
        filename,
        mimeType: 'application/octet-stream',
        error: `Unsupported export format: ${options.format}`,
      };
  }

  if (result.success && result.data) {
    downloadFile(result.data, result.filename, result.mimeType);
  }

  return result;
}

/**
 * Extract animations from scene
 */
function extractAnimations(scene: THREE.Object3D): THREE.AnimationClip[] {
  const animations: THREE.AnimationClip[] = [];

  scene.traverse((child) => {
    if (child instanceof THREE.Mesh && 'animations' in child) {
      const childAnimations = (child as unknown as { animations: THREE.AnimationClip[] }).animations;
      if (Array.isArray(childAnimations)) {
        animations.push(...childAnimations);
      }
    }
  });

  return animations;
}

/**
 * Validate scene before export
 */
export function validateScene(scene: THREE.Object3D): { valid: boolean; errors: string[] } {
  const errors: string[] = [];

  if (!scene) {
    errors.push('Scene is not defined');
    return { valid: false, errors };
  }

  let hasMesh = false;
  let totalVertices = 0;

  scene.traverse((child) => {
    if (child instanceof THREE.Mesh) {
      hasMesh = true;
      const geometry = child.geometry as THREE.BufferGeometry;
      if (geometry) {
        const positionAttribute = geometry.getAttribute('position');
        if (positionAttribute) {
          totalVertices += positionAttribute.count;
        }
      }
    }
  });

  if (!hasMesh) {
    errors.push('No meshes found in scene');
  }

  if (totalVertices === 0) {
    errors.push('Scene contains no vertices');
  }

  // Warn if mesh is too large (>10M vertices)
  if (totalVertices > 10000000) {
    errors.push('Scene has too many vertices (>10M). Export may fail or be slow.');
  }

  return { valid: errors.length === 0, errors };
}
