/**
 * 3D Model Export Utilities
 * Handles exporting 3D models to various formats (STL, GLTF, GLB, etc.)
 */

import * as THREE from 'three';
import { STLExporter } from 'three/examples/jsm/exporters/STLExporter.js';
import { GLTFExporter } from 'three/examples/jsm/exporters/GLTFExporter.js';

export interface ExportOptions {
  format: 'stl' | 'glb' | 'gltf' | 'obj';
  binary?: boolean;
  onProgress?: (progress: number) => void;
}

export interface ExportResult {
  success: boolean;
  data?: ArrayBuffer | DataView | string;
  filename: string;
  mimeType: string;
  error?: string;
}

/**
 * Export 3D scene to STL format
 * Supports both ASCII and binary STL formats
 */
export async function exportToSTL(
  scene: THREE.Object3D,
  filename: string,
  binary: boolean = false,
): Promise<ExportResult> {
  try {
    const exporter = new STLExporter();

    // Clone scene to avoid modifying original
    const sceneToExport = scene.clone();

    // Parse the scene (exporter expects Object3D, not geometry)
    const data = exporter.parse(sceneToExport, { binary });
    const mimeType = binary ? 'application/octet-stream' : 'text/plain';
    const outputFilename = filename.replace(/\.[^/.]+$/, '') + '.stl';

    return {
      success: true,
      data,
      filename: outputFilename,
      mimeType,
    };
  } catch (error) {
    return {
      success: false,
      filename,
      mimeType: 'application/octet-stream',
      error: `Failed to export STL: ${error instanceof Error ? error.message : String(error)}`,
    };
  }
}

/**
 * Export 3D scene to GLTF/GLB format
 * GLB is the binary version of GLTF
 */
export async function exportToGLTF(
  scene: THREE.Object3D,
  filename: string,
  binary: boolean = true,
  onProgress?: (progress: number) => void,
): Promise<ExportResult> {
  return new Promise((resolve) => {
    try {
      const exporter = new GLTFExporter();

      const options: Record<string, unknown> = {
        binary,
        animations: extractAnimations(scene),
        maxTextureSize: 2048,
      };

      // Track progress manually
      let progressTracked = 0;
      const progressInterval = setInterval(() => {
        if (progressTracked < 90) {
          progressTracked += Math.random() * 20;
          onProgress?.(Math.min(progressTracked, 90));
        }
      }, 100);

      exporter.parse(
        scene,
        (result) => {
          clearInterval(progressInterval);
          onProgress?.(100);

          let data: ArrayBuffer | string;
          let mimeType: string;
          const extension = binary ? '.glb' : '.gltf';
          const outputFilename = filename.replace(/\.[^/.]+$/, '') + extension;

          if (binary) {
            data = result as ArrayBuffer;
            mimeType = 'application/octet-stream';
          } else {
            data = JSON.stringify(result, null, 2);
            mimeType = 'application/json';
          }

          resolve({
            success: true,
            data,
            filename: outputFilename,
            mimeType,
          });
        },
        (_error) => {
          // Error callback - just log it
          console.error('GLTF Export error:', _error);
        },
        options as Record<string, unknown>,
      );

      // Set timeout for export completion
      setTimeout(() => {
        clearInterval(progressInterval);
        resolve({
          success: false,
          filename,
          mimeType: 'application/octet-stream',
          error: 'GLTF export timeout',
        });
      }, 30000); // 30 second timeout
    } catch (error) {
      resolve({
        success: false,
        filename,
        mimeType: 'application/octet-stream',
        error: `Failed to export GLTF: ${error instanceof Error ? error.message : String(error)}`,
      });
    }
  });
}

/**
 * Export 3D scene to OBJ format
 * Basic OBJ export (geometry only, no materials)
 */
export async function exportToOBJ(
  scene: THREE.Object3D,
  filename: string,
): Promise<ExportResult> {
  try {
    const geometries: THREE.BufferGeometry[] = [];
    let vertexOffset = 0;
    let objData = '# Generated by TSplineForge\n';
    objData += `# File: ${filename}\n`;
    objData += `# Date: ${new Date().toISOString()}\n\n`;

    // Traverse scene and collect geometries
    scene.traverse((child) => {
      if (child instanceof THREE.Mesh) {
        geometries.push(child.geometry as THREE.BufferGeometry);
      }
    });

    if (geometries.length === 0) {
      throw new Error('No geometries found in scene');
    }

    // Convert geometries to OBJ format
    geometries.forEach((geometry, meshIndex) => {
      objData += `g Mesh_${meshIndex}\n`;

      // Get position attribute
      const positionAttribute = geometry.getAttribute('position');
      if (positionAttribute) {
        const positions = positionAttribute.array as Float32Array;
        for (let i = 0; i < positions.length; i += 3) {
          objData += `v ${positions[i]} ${positions[i + 1]} ${positions[i + 2]}\n`;
        }
      }

      // Get index or create faces
      const index = geometry.getIndex();
      if (index) {
        const indices = index.array as Uint32Array | Uint16Array | Uint8Array;
        for (let i = 0; i < indices.length; i += 3) {
          const a = (indices[i] as number) + vertexOffset + 1;
          const b = (indices[i + 1] as number) + vertexOffset + 1;
          const c = (indices[i + 2] as number) + vertexOffset + 1;
          objData += `f ${a} ${b} ${c}\n`;
        }
      }

      vertexOffset += (positionAttribute?.array as Float32Array).length / 3;
    });

    const outputFilename = filename.replace(/\.[^/.]+$/, '') + '.obj';

    return {
      success: true,
      data: objData,
      filename: outputFilename,
      mimeType: 'text/plain',
    };
  } catch (error) {
    return {
      success: false,
      filename,
      mimeType: 'text/plain',
      error: `Failed to export OBJ: ${error instanceof Error ? error.message : String(error)}`,
    };
  }
}

/**
 * Download exported file to client
 */
export function downloadFile(
  data: ArrayBuffer | DataView | string,
  filename: string,
  mimeType: string,
): void {
  let blobParts: BlobPart[];

  if (typeof data === 'string') {
    blobParts = [data];
  } else if (data instanceof DataView) {
    // Convert DataView to Uint8Array to avoid SharedArrayBuffer issues
    const uint8Array = new Uint8Array(data.buffer, data.byteOffset, data.byteLength);
    blobParts = [uint8Array as unknown as BlobPart];
  } else {
    blobParts = [data as unknown as BlobPart];
  }

  const blob = new Blob(blobParts, { type: mimeType });

  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

/**
 * Export with automatic download
 */
export async function exportAndDownload(
  scene: THREE.Object3D,
  filename: string,
  options: ExportOptions,
): Promise<ExportResult> {
  let result: ExportResult;

  switch (options.format) {
    case 'stl':
      result = await exportToSTL(scene, filename, options.binary ?? true);
      break;
    case 'glb':
      result = await exportToGLTF(scene, filename, true, options.onProgress);
      break;
    case 'gltf':
      result = await exportToGLTF(scene, filename, false, options.onProgress);
      break;
    case 'obj':
      result = await exportToOBJ(scene, filename);
      break;
    default:
      result = {
        success: false,
        filename,
        mimeType: 'application/octet-stream',
        error: `Unsupported export format: ${options.format}`,
      };
  }

  if (result.success && result.data) {
    downloadFile(result.data, result.filename, result.mimeType);
  }

  return result;
}

/**
 * Extract animations from scene
 */
function extractAnimations(scene: THREE.Object3D): THREE.AnimationClip[] {
  const animations: THREE.AnimationClip[] = [];

  scene.traverse((child) => {
    if (child instanceof THREE.Mesh && 'animations' in child) {
      const childAnimations = (child as unknown as { animations: THREE.AnimationClip[] }).animations;
      if (Array.isArray(childAnimations)) {
        animations.push(...childAnimations);
      }
    }
  });

  return animations;
}

/**
 * Validate scene before export
 */
export function validateScene(scene: THREE.Object3D): { valid: boolean; errors: string[] } {
  const errors: string[] = [];

  if (!scene) {
    errors.push('Scene is not defined');
    return { valid: false, errors };
  }

  let hasMesh = false;
  let totalVertices = 0;

  scene.traverse((child) => {
    if (child instanceof THREE.Mesh) {
      hasMesh = true;
      const geometry = child.geometry as THREE.BufferGeometry;
      if (geometry) {
        const positionAttribute = geometry.getAttribute('position');
        if (positionAttribute) {
          totalVertices += positionAttribute.count;
        }
      }
    }
  });

  if (!hasMesh) {
    errors.push('No meshes found in scene');
  }

  if (totalVertices === 0) {
    errors.push('Scene contains no vertices');
  }

  // Warn if mesh is too large (>10M vertices)
  if (totalVertices > 10000000) {
    errors.push('Scene has too many vertices (>10M). Export may fail or be slow.');
  }

  return { valid: errors.length === 0, errors };
}
