'use client';

import * as THREE from 'three';
import { STLExporter, GLTFExporter, OBJExporter } from 'three-stdlib';
import type { ExportFormat, ExportUnit } from './exportFormats';
import { UNIT_SCALES } from './exportFormats';

/**
 * Converts a Three.js geometry or group to a solid mesh object
 * This ensures we have a proper mesh for export, not just raw geometry
 */
function ensureMesh(geometry: THREE.BufferGeometry | THREE.Group): THREE.Mesh | THREE.Group {
  if (geometry instanceof THREE.Group) {
    return geometry;
  }

  // If it's a BufferGeometry, create a mesh from it
  const material = new THREE.MeshStandardMaterial({
    color: 0x3b82f6,
    roughness: 0.7,
    metalness: 0,
  });

  return new THREE.Mesh(geometry, material);
}

/**
 * Converts geometry to STL format (binary)
 */
async function exportToSTL(
  geometry: THREE.BufferGeometry | THREE.Group,
  filename: string
): Promise<Blob> {
  const mesh = ensureMesh(geometry);
  const exporter = new STLExporter();
  const stlData = exporter.parse(mesh, { binary: true });

  return new Blob([stlData], { type: 'model/stl' });
}

/**
 * Converts geometry to glTF format (JSON + separate buffers)
 */
async function exportToGLTF(
  geometry: THREE.BufferGeometry | THREE.Group,
  filename: string
): Promise<Blob> {
  const mesh = ensureMesh(geometry);
  const scene = new THREE.Scene();
  scene.add(mesh);

  return new Promise((resolve, reject) => {
    const exporter = new GLTFExporter();

    exporter.parse(
      scene,
      (gltf) => {
        // Convert the parsed glTF to JSON string
        const json = JSON.stringify(gltf);
        const blob = new Blob([json], { type: 'model/gltf+json' });
        resolve(blob);
      },
      (error) => {
        reject(new Error(`glTF export failed: ${error.message}`));
      }
    );
  });
}

/**
 * Converts geometry to GLB format (binary glTF)
 */
async function exportToGLB(
  geometry: THREE.BufferGeometry | THREE.Group,
  filename: string
): Promise<Blob> {
  const mesh = ensureMesh(geometry);
  const scene = new THREE.Scene();
  scene.add(mesh);

  return new Promise((resolve, reject) => {
    const exporter = new GLTFExporter();

    exporter.parse(
      scene,
      (gltf) => {
        // GLB is the binary representation
        const blob = new Blob([JSON.stringify(gltf)], { type: 'model/gltf-binary' });
        resolve(blob);
      },
      { binary: true },
      (error) => {
        reject(new Error(`GLB export failed: ${error.message}`));
      }
    );
  });
}

/**
 * Converts geometry to OBJ format
 */
async function exportToOBJ(
  geometry: THREE.BufferGeometry | THREE.Group,
  filename: string
): Promise<Blob> {
  const mesh = ensureMesh(geometry);
  const exporter = new OBJExporter();
  const objData = exporter.parse(mesh);

  return new Blob([objData], { type: 'model/obj' });
}

/**
 * Creates a simple STEP-like text representation
 * (Not a true STEP file, but provides export capability)
 */
async function exportToSTEP(
  geometry: THREE.BufferGeometry | THREE.Group,
  filename: string
): Promise<Blob> {
  const mesh = ensureMesh(geometry);

  // For now, we'll export as OBJ but with a .step extension
  // A true STEP exporter would require a proper CAD kernel
  const exporter = new OBJExporter();
  const objData = exporter.parse(mesh);

  // Add STEP-like header comment
  const stepData = `$ STEP file exported by TSplineForge
$ This is a simplified STEP representation
$ For production use, import the OBJ or STL format instead
$
${objData}`;

  return new Blob([stepData], { type: 'application/step' });
}

/**
 * Creates a simple IGES-like text representation
 * (Not a true IGES file, but provides export capability)
 */
async function exportToIGES(
  geometry: THREE.BufferGeometry | THREE.Group,
  filename: string
): Promise<Blob> {
  const mesh = ensureMesh(geometry);

  // For now, we'll export as OBJ but with a .iges extension
  // A true IGES exporter would require a proper CAD kernel
  const exporter = new OBJExporter();
  const objData = exporter.parse(mesh);

  // Add IGES-like header
  const igesData = `S      1
     Initial Graphics Exchange Specification
     File: ${filename}.iges
     Generated by TSplineForge
${objData}`;

  return new Blob([igesData], { type: 'application/iges' });
}

/**
 * Main export function that routes to the appropriate exporter
 */
export async function exportGeometry(
  geometry: THREE.BufferGeometry | THREE.Group | null,
  format: ExportFormat,
  filename: string,
  options?: {
    unit?: ExportUnit;
    preserveColors?: boolean;
    preserveMaterials?: boolean;
  }
): Promise<Blob> {
  if (!geometry) {
    throw new Error('No geometry provided for export');
  }

  // Clone geometry if needed to avoid modifying original
  let exportGeometry = geometry;

  // Apply unit scaling if needed
  if (options?.unit && options.unit !== 'mm') {
    const scale = UNIT_SCALES[options.unit] / UNIT_SCALES['mm'];
    if (exportGeometry instanceof THREE.Group) {
      exportGeometry = exportGeometry.clone();
      exportGeometry.scale.multiplyScalar(scale);
    } else {
      exportGeometry = exportGeometry.clone();
      exportGeometry.scale(scale, scale, scale);
    }
  }

  let blob: Blob;

  switch (format) {
    case 'stl':
      blob = await exportToSTL(exportGeometry, filename);
      break;
    case 'gltf':
      blob = await exportToGLTF(exportGeometry, filename);
      break;
    case 'glb':
      blob = await exportToGLB(exportGeometry, filename);
      break;
    case 'obj':
      blob = await exportToOBJ(exportGeometry, filename);
      break;
    case 'step':
      blob = await exportToSTEP(exportGeometry, filename);
      break;
    case 'iges':
      blob = await exportToIGES(exportGeometry, filename);
      break;
    default:
      throw new Error(`Unsupported export format: ${format}`);
  }

  return blob;
}

/**
 * Triggers a download of the blob in the browser
 */
export function downloadBlob(blob: Blob, filename: string): void {
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);

  try {
    link.click();
  } finally {
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  }
}

/**
 * Combined export and download function
 */
export async function exportAndDownload(
  geometry: THREE.BufferGeometry | THREE.Group | null,
  format: ExportFormat,
  filename: string,
  options?: {
    unit?: ExportUnit;
    preserveColors?: boolean;
    preserveMaterials?: boolean;
  }
): Promise<{ blob: Blob; size: number }> {
  const blob = await exportGeometry(geometry, format, filename, options);
  const fullFilename = `${filename}.${getExtension(format)}`;
  downloadBlob(blob, fullFilename);

  return {
    blob,
    size: blob.size,
  };
}

/**
 * Helper to get file extension for a format
 */
function getExtension(format: ExportFormat): string {
  const extensions: Record<ExportFormat, string> = {
    step: 'step',
    iges: 'iges',
    stl: 'stl',
    gltf: 'gltf',
    obj: 'obj',
    glb: 'glb',
  };
  return extensions[format];
}
